// Actions
export const ACTIONS = {
  UPDATE_ALL: 'UPDATE_ALL',
  UPDATED_ALL: 'UPDATED_ALL',
  UPDATE_ACTIVE_TAG: 'UPDATE_ACTIVE_TAG',
  UPDATED_ACTIVE_TAG: 'UPDATED_ACTIVE_TAG',
};

// Getters
export const GETTERS = {
  PARENT_INDEX: 'PARENT_INDEX',
  CHILDREN_INDEX: 'CHILDREN_INDEX',
  TAG_TITLE: 'TAG_TITLE',
  TAG_SUBTITLE: 'TAG_SUBTITLE',
  FIGURES: 'FIGURES',
  FIGURE: 'FIGURE',
};

// KEY_EVENTS
export const KEY_EVENTS = {
  TOGGLE_TREE: 'command+shift+left',
  TOGGLE_INFO: 'command+shift+right',
  MOVE_UP: 'up',
  MOVE_DOWN: 'down',
};
